### ISSUE TITLE
No CDR

### ISSUE THREAD

**Issue by bigtoodog** [tiredofit/docker-freepbx#57]
I configured this docker with embedded DB, but there is NO cdr recorded after making some calls.

Another issue is apache service NOT started after restarting the docker.

**Comment by tiredofit** [comment]
Ahh - CDR. what a mess. I had my own little personal hell with it myself, however on the external DB.
For that one - let's see your ```/etc/freepbx.conf```` (omit password please) and also `/etc/odbc.ini`. There is also a way on the Admin -> Advanced Settings to check some of the CDR settings - I found it was best with mine being blank, however yours may be different. I really struggled with the embedded DB and added it as a request, but I haven't done considerable testing on it.

As for the apache issue - Can I have a full `docker-compose logs` output to review?

**Comment by bigtoodog** [comment]
Here is the log:

[docker-compose.log](https://github.com/tiredofit/docker-freepbx/files/2882602/docker-compose.log)

**Comment by tiredofit** [comment]
Thanks for this - Line 42 sticks out to me as an issue with core/framework. Also Line 1109 with Mongo, although not critical.

The process error you are getting on second startup is looking for a file called `/data/.installed` (Line 297 /etc/cont-init.d/10-freepbx - Which gets written after a successful installation. Are you using something similar to my example docker-compose.yml file? 

If you could - Also try setting `DEBUG_MODE=TRUE` and starting from scratch, I'd be very interested in seeing that log output as well, however I have something to work with early tomorrow morning when back in the office.

**Comment by bigtoodog** [comment]
Yes, I'm using your example docker-compose.yml file with slight modification for embedding DB and nginx reverse proxy container as below (I also built the image with your dockerfile without modification except disable fax module due to unable to download spandsp):

version: '2'

services:
  freepbx-app:
    container_name: freepbx-app
    image: bs/freepbx15:v1
    ports:
     #### If you aren't using a reverse proxy
     #- 80:80
     #### If you want SSL Support and not using a reverse proxy
     #- 443:443
      - 6500:6500
      - 6510:6510
      - 18000-18100:18000-18100/udp
     #### Flash Operator Panel
     # - 4445:4445
    volumes:
      - ./certs:/certs
      - ./data:/data
      - ./logs:/var/log
      - ./data/www:/var/www/html
     ### Only Enable this option below if you set DB_EMBEDDED=TRUE
      - ./db:/var/lib/mysql
     ### You can drop custom files overtop of the image if you have made modifications to modules/css/whatever - Use with care
     #- ./assets/custom:/assets/custom

    environment: 
      - VIRTUAL_HOST=xxxx
      - VIRTUAL_NETWORK=webproxy
     ### If you want to connect to the SSL Enabled Container 
      #- VIRTUAL_PORT=443
      #- VIRTUAL_PROTO=https
     # - VIRTUAL_PORT=80
      #- LETSENCRYPT_HOST=xxx
      #- LETSENCRYPT_EMAIL=xxx

     # - ZABBIX_HOSTNAME=freepbx-app

      - RTP_START=18000
      - RTP_FINISH=18100
    
     ## Use for External MySQL Server
      - DB_EMBEDDED=TRUE
      
     ## added by dhb
      - UCP_FIRST=FALSE

     ### These are only necessary if DB_EMBEDDED=FALSE
     # - DB_HOST=freepbx-db
     # - DB_PORT=3306
     # - DB_NAME=asterisk
     # - DB_USER=asterisk
     # - DB_PASS=asteriskpass
    
     ### If you are using TLS Support for Apache to listen on 443 in the container drop them in /certs and set these:
     #- TLS_CERT=cert.pem
     #- TLS_KEY=key.pem
     
    restart: always
    networks:
      - proxy-tier

    ### These final lines are for Fail2ban. If you don't want, comment and also add ENABLE_FAIL2BAN=FALSE to your environment
    cap_add:
      - NET_ADMIN
    privileged: true

#  freepbx-db:
#    container_name: freepbx-db
#    image: tiredofit/mariadb
#    restart: always
#    volumes:
#      - ./db:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=asterisk
#      - MYSQL_USER=asterisk
#      - MYSQL_PASSWORD=asteriskpass
#    networks:
#      - proxy-tier
#
#  freepbx-db-backup:
#    container_name: freepbx-db-backup
#    image: tiredofit/db-backup
#    links:
#     - freepbx-db
#    volumes:
#      - ./dbbackup:/backup
#    environment:
#      - ZABBIX_HOSTNAME=freepbx-db-backup
#      - DB_HOST=freepbx-db
#      - DB_TYPE=mariadb
#      - DB_NAME=asterisk
#      - DB_USER=asterisk
#      - DB_PASS=asteriskpass
#      - DB_DUMP_FREQ=1440
#      - DB_DUMP_BEGIN=0000
#      - DB_CLEANUP_TIME=8640
#      - COMPRESSION=BZ
#      - MD5=TRUE
#    networks:
#      - proxy-tier
#    restart: always

networks:
  proxy-tier:
    external:
      name: webproxy

**Comment by tiredofit** [comment]
Thanks for all the above including spandsp. I'll work in a temporary fix for that as well while soft-switch.org is down. Let me get back to you on this, I need to run some tests. I'll be updating the `develop` branch as I work with this, so feel free to watch commits and pull latest `tiredofit/freepbx:develop` from the Docker Hub if you want to test out and see progress.

**Comment by tiredofit** [comment]
Thanks, Found the issue with secondary starts. Going to push a new release for that right away along with some minor DB fixes. Will get to the CDR component shortly.

**Comment by tiredofit** [comment]
Yeesh, I broke that one entirely. New version (`3.3`, `15-3.3`, `latest`, `15`) fix the mess I created yesterday. Also updated to Asterisk 16.2.0

**Comment by bendhb** [comment]
The new update resolved 2nd startup issue. Thanks.

However there is still NO cdr for embedded DB.

**Comment by tiredofit** [comment]
Right - I still need to look into this one. What would help as well is if you privately got me a copy of your /var/log/full that has at least 1 outbound call attempt in it. Also as above get me a copy of your /etc/odbc.ini and /etc/asterisk/freepbx.conf privately and I can see if I can recreate. I have a theory but nothing to confirm at this time. I'll spin up the embedded copy this weekend, was distracted with the other issues you identified. You can find my email in the changelog or dave @ my githubusername .ca

**Comment by tiredofit** [comment]
Issue has been resolved with CDR - related to mariadb connector 3.x not being compatible with Asterisk. Downgraded to 2.x series and pushed new image `3.3.1`.

**Comment by salty-physics** [comment]
I don't using embedded DB - fresh instalation 2 days ago with mariadb:lastest
I pull lastest version of  tiredofit/freepbx but i still don't get CDR working - all reports are empty

**Comment by tiredofit** [comment]
Hi Gritoo - Try the latest release. About 11 hours ago I put a new build out that should work.

**Comment by salty-physics** [comment]
Unfortunately not working - tested on:
`
version: '3.1'

services:

  serwer:
    image: tiredofit/freepbx:15-3.3.1
    ports:
      - "18000-18200:18000-18200/udp"
      - "5060:5060/udp"
    environment:
      - VIRTUAL_HOST=freepbx
      - ENABLE_FAIL2BAN=FALSE
      - DB_EMBEDDED=FALSE
      - DB_NAME=asterisk
      - DB_USER=asterisk
      - DB_PASS=asteriskpass
      - DB_HOST=db
      - RTP_START=18000
      - RTP_FINISH=18200
      - UCP_FIRST=FALSE
      - ENABLE_FOP=FALSE
    volumes:
      - /docker/mounts/freepbx/log:/var/log/
      - /docker/mounts/freepbx/certs:/certs
      - /docker/mounts/freepbx/www:/var/www/html
      - /docker/mounts/freepbx/data:/data
    networks:
      - siecproxy
      - local
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk
      - MYSQL_PASSWORD=asteriskpass
    volumes:
      - /docker/mounts/freepbx/mysql:/var/lib/mysql
    networks:
      - local

networks:
  siecproxy:
    external: true
  local:

`

**Comment by tiredofit** [comment]
Send me a copy of your /var/log/asterisk/full to my email - it's in the Changelog or dave @ mygithubusername .ca - Hard to tell as I cannot recreate.

**Comment by salty-physics** [comment]
I send it on friday

**Comment by salty-physics** [comment]
I found some errors on SQL Insert in my logs:

> [2019-03-08 02:49:58] WARNING[1162]: res_odbc.c:439 ast_odbc_print_errors: SQL Execute returned an error: 22007: [ma-2.0.18][10.3.13-MariaDB-1:10.3.13+maria~bionic]Incorrect string value: '\xC5\x81ukas...' for column `asterisk`.`cel`.`cid_name` at row 1
>[2019-03-08 02:49:58] WARNING[1162]: res_odbc.c:386 ast_odbc_prepare_and_execute: SQL Execute error -1!
>[2019-03-08 02:49:58] WARNING[1162]: cel_odbc.c:788 odbc_log: Insert failed on 'asteriskcdrdb:cel'.  CEL failed: INSERT INTO cel (eventtype, eventtime, cid_name, cid_num, cid_ani, cid_rdnis, cid_dnid, exten, context, channame, appname, appdata, amaflags, accountcode, uniqueid, linkedid, peer, userdeftype, extra) VALUES ('LINKEDID_END', {ts '2019-03-08 02:49:58.651790'}, 'PhoneUser', '54', '54', '', '92', 'h', 'from-internal', 'PJSIP/54-000000e2', '', '', 3, '', '1552042073.226', '1552042073.226', '', '', '')
I get these errors after any finished call
