### ISSUE TITLE
No fax module detected

### ISSUE THREAD

**Issue by salty-physics** [tiredofit/docker-freepbx#78]
I cannot configure fax on user
on fax tab i get error:
> ERROR:` No FAX modules detected!
> Fax-related dialplan will NOT be generated.
> This module requires Fax for Asterisk (res_fax_digium.so) or spandsp based app_fax (res_fax_spandsp.so) to function.

**Comment by tiredofit** [comment]
Hi what tag/release are you using? I released a new version the other day with SpanDSP compiled in.

**Comment by salty-physics** [comment]
tiredofit/freepbx:15-3.3.1
I missed new versions :( my mistake

**Comment by salty-physics** [comment]
after change to tiredofit/freepbx:15-3.6 i still get this error
aslo [my problem with CDR ](https://github.com/tiredofit/docker-freepbx/issues/68) still exist too
What i shuld do after update version ? run any script ? i only changed version in docker compose (from 3.3.1 to 3.6) stop and start my stack

**Comment by tiredofit** [comment]
Hrm. This is where I am a bit lost then what I am missing. If you can do some digging as to what module or if anything needs to run in a script I will merge this in. I have compiled spandsp and compiled in app_fax when compiling asterisk, not sure what else is required?

**Comment by salty-physics** [comment]
I can't find what is required to make it works so i configured fax outside of my company.

**Comment by lights0123** [comment]
@tiredofit in /usr/lib/asterisk/modules there's `app_fax.so`, but the file `res_fax_spandsp.so` does not exist, nor is there any file that has `span` in it.
