### ISSUE TITLE
logrotate not found by crontab

### ISSUE THREAD

**Issue by sincejune** [tiredofit/docker-freepbx#86]
Hi bro:

I set up an instance with image `tiredofit/freepbx:15`. It's awesome.

But I found that the asterisk logs won't be rotated while the relevant rules is already defined under `/etc/logrotate.d/`. I did some research on it and finally found that it's because `crontab` can't find the `logrotate` command.

I can't modify the crontab rules because it will be [overrided](https://github.com/tiredofit/docker-debian/blob/stretch/install/etc/s6/services/03-cron/run#L11) every when the container restart. So I think the best solution is to use absolute path for `logrotate` like `59 23 * * * /usr/sbin/logrotate -f /etc/logrotate.d/* >/dev/null 2>&1`.

**Comment by tiredofit** [comment]
Hi there. I'll update my base image (Debian) which contains this file. It'll trigger a mass build on Docker Hub of alot of my images, but will be fixed in the next `latest` release. Typically takes 2 days.

In the meantime, if you mapped a volume to /assets/cron-custom and created a file in there, that will get added to the crontab on bootup.

**Comment by sincejune** [comment]
Thanks for paying attention to this. It would be lovely if this get fixed.

**Comment by tiredofit** [comment]
Darnit, the image never built correctly. I am away now for the next week at a conference, Will have to review this when I return. The base image has been updated but something has hung along the way.

**Comment by sincejune** [comment]
Hi bro. Not to rush you, but is there any update on this?

**Comment by tiredofit** [comment]
I pushed a new copy of the base image (tiredofit/debian) earlier on today. It should be in the queue for a new build which should solve this. I looked on Docker Hub and it's said a new freepbx:latest has been pushed 12 hours ago. Can you check if this meets what you are after?

If it doesn't, I will manually build one for you and replace :latest with a working ver. Docker Hub can be quite finnicky with automated builds.

**Comment by sincejune** [comment]
Looks like it need to remove previous storage to get it working.
I tried to delete my container to let it re-create but the new container doesn't work to me. When I try to set up a brand new one, that works.

**Comment by sincejune** [comment]
It still doesn't work for me.
But `tiredofit/nodejs:12-debian-latest` works, so I think `freepbx` might was built using the old image.

**Comment by tiredofit** [comment]
I'm going to manually push a `tiredofit/freepbx:3.7.3` up to the Docker Hub that uses fresh builds on my own system just to make sure this is not a Docker Hub issue. I find that when I use a few base images things  can get out of sync.

**Comment by tiredofit** [comment]
OK! It's up and available now. Let me know how that works. Sounds like I may need to dust off some of the Docker Hub configuration and redo some of my mappings. I admit I haven't had much time to keep things maintained as of late.

**Comment by sincejune** [comment]
Verified the problem had been fixed in the new image.

Thanks a lot for your help 👏

**Comment by tiredofit** [comment]
Right on! Sorry about the delay for this.
